addpath(fullfile(pwd, 'Contact'));
addpath(fullfile(pwd, 'arms'));
addpath(fullfile(pwd, 'plotting'));
addpath(fullfile(pwd, 'worlds'));
addpath(fullfile(pwd, 'pathPlanning'));
addpath(fullfile(pwd, 'pathPlanning/contactInvariantOptimization'));
addpath(fullfile(pwd, 'trajectorySmoothing'));
addpath(fullfile(pwd, 'kinematics'));
addpath(fullfile(pwd, 'control'));
addpath(fullfile(pwd, 'policyRRT'));
addpath(fullfile(pwd, 'policyRRT/policies'));
addpath(fullfile(pwd, 'policyRRT/modularRRT'));
addpath(fullfile(pwd, 'policyRRT/modularRRT/core'));
addpath(fullfile(pwd, 'policyRRT/modularRRT/extend'));
addpath(fullfile(pwd, 'policyRRT/modularRRT/sampling'));
addpath(fullfile(pwd, '../matlab_SEA/plottingTools'));
addpath(fullfile(pwd, '../matlab_SEA/plottingTools/stl'));
addpath(fullfile('/home/puneet/Documents/MATLAB/STLRead/'));
addpath(genpath('/home/puneet/contactInvariantOptimization/hebi/'));
addpath(genpath('/home/puneet/contactInvariantOptimization/matlab_SEA/'));
addpath(fullfile(pwd, '/fkTools/'));
addpath(fullfile('/home/puneet/Documents/MATLAB/STLRead'));